### ISSUE TITLE
Weather Issues

### ISSUE THREAD

**Issue by lpCoercion** [kaptain-kavern/EcosystemOverhaul#10]
I have been testing out the mod, and noticed that every new game starts on Clear (Tropical).

I decided to remove Clear (Tropical) from the biome, because I dont think it works. So, after removing it from BiomeDefs, the rainforest weather starts on Clear, and I eventually got the following error (I assume when the weather tries to change):

![.](http://imgur.com/lUx4DXD.jpg)

Any ideas on how to remove it?

**Comment by kaptain-kavern** [comment]
Yep is exactly what I was referring to, the last past days, when I was talking about the weather crash/bug.  I had to try to decrypt the C# part of the code. And from the little that I understood : despite having the possibility to set things in the XML files, the system looks pretty rigid regarding about how the C# part behave. 

I don't understand C# a lot so it's more a guessing than a fact but in the end it seems to only works when value are more or less the same as in core.

 And it looks like your forced to start with a clear weather (in fact now that I think about it I can't remember having start a new game under rain or snow)

**Comment by lpCoercion** [comment]
So, we cant change these values without using CCL and C#?

**Comment by lpCoercion** [comment]
I asked around on Slack and I got some feedback on our weather problem. I am going to try and mess around in C# to fix this... will let you know what I figure out lol

**Comment by lpCoercion** [comment]
So basically we have two options:

I need to create a dll using C# to tick every few seconds and check the weather. If it is set to clear, it will force it to tropical rain. then, I can either:

1. create a new map condition that calls that dll. this would require the player to choose this condition anytime they have a new scenerio... or

2. create a new condition in HediffGiverSets.xml to call the dll. this i what is used to check if a pawn gets hypothermia etc. it would be active all of the time and is probably our best option.. but may have more compatibility issues

**Comment by lpCoercion** [comment]
So, first off, it appears that the temperature isnt set by the weather. That temp range is actually something that allows or prevents the weather based on map temperature. So, it doesnt start snowing during a heat wave.

It looks like I will have to create a a hediff (what checks pawns for health issues) to turn on a custom map condition. That map condition will call a dll file (C#) to tick every few seconds and check the current weather. If it is clear (and the biome is in the rainforest), it will force the weather to tropical rain. The map condition will then also increase the overall temperature in rainforest using that dll file.

**Comment by kaptain-kavern** [comment]
All of this is "just" for not starting with "clear" weather ? I mean, again, it's not that I don't like it (or don't want to learn more C#) but don't you think it's another thing that get us to loose our focus and delay again the "full" release date?

**Comment by lpCoercion** [comment]
Yeah. thats a good point. Lets just focus on adding plants and animals in this mod. 

Maybe I will create a separate realistic weathers mod later.

**Comment by kaptain-kavern** [comment]
Or we can focus on improving the weather _after_ releasing a playable version :wink:
