### ISSUE TITLE
Github Name & Description

### ISSUE THREAD

**Issue by lpCoercion** [kaptain-kavern/EcosystemOverhaul#11]
Can you update the mod title and description on Github to the below. This will be the final name and description for release. I updated the About file already. "CK" is the first letters of our usernames.

_Name_: CK - Animal Pack & Plant Pack

_Description_: The purpose of this mod is to add a significant amount of new animals and plants to the game and increase fauna and flora biome diversity. New factions have been added to control biome pack animals and introduce new trade resources.

**Comment by kaptain-kavern** [comment]
Done
