### ISSUE TITLE
Animal Sculptures

### ISSUE THREAD

**Issue by lpCoercion** [kaptain-kavern/EcosystemOverhaul#20]
What is your thought on creating animal sculptures for art?

I would basically remove the color from certain animals, put them on a stand and they would be able to be made at an art table using the same vanilla art mats.

For example,

small: peafowl, cobra, etc.
large: tiger, okapi, etc
grand: elephant, gorilla, etc

**Comment by kaptain-kavern** [comment]
I saw you created another repo, sry I haven't reply earlier. In theory that seems doable but I haven't try to mod sculptures yet. I have to look how feasible it is. The only point I fear about is the description of sculptures and how they are "attached" to the building in the code (ATM I really have no idea how its done but I've never look at it)

I will do search and come back to you

**Comment by lpCoercion** [comment]
no worries. I wasnt sure if you were interested. This would be a separate mod, but we can always do it together. I figure all we need to do is copy the vanilla statue defs, rename them and link new textures.

**Comment by lpCoercion** [comment]
if you are interested, how do i delete my repo?

**Comment by lpCoercion** [comment]
If you want to do a hunting mod by the way, I can do art for that too. maybe combine it with this sculpture mod and call it "CK - Animal Crafting"

could also make it dependent on our animal mos

**Comment by kaptain-kavern** [comment]
Hey thanks for the offering. I was about to tell you the same :p 

We could even go nuts and make a full taxidermy mods ^^ Sculpture or stuffed animals seems similar to me. 

Harvesting horns for ivory, or trophies, stuffed animals (there was a mod that do that in the past; and another one that permit to turn animals corpses into carpet/rugs), and any other ideas we can cram into it ^^ . Hell , in dwarf fortress there is a complete bone industry lol

**Comment by lpCoercion** [comment]
I do like the idea, but I would like to keep everything as simple as possible.

**Comment by kaptain-kavern** [comment]
- Link to the "stuffed animals" mod : https://ludeon.com/forums/index.php?topic=2569.0

**Comment by lpCoercion** [comment]
So just a corpse and cloth would make a static version?

**Comment by kaptain-kavern** [comment]
Yep that's how this mod works. 

The question I got is : do we reinvent the wheel (redo all this one is already doing) or do we just make it with our animals - I [asked to ItcheaFlea if it's OK with him](https://ludeon.com/forums/index.php?topic=2569.msg269109#msg269109)

**Comment by lpCoercion** [comment]
maybe just ask him if he wants to make a patch for our mod?

**Comment by kaptain-kavern** [comment]
Turns out it's me that have offered to do a patch :p 
(sorry for the "silence", it was A Dog Said update day today ^^)

**Comment by lpCoercion** [comment]
no worries. I will be out of town for a few days
