### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by lpCoercion** [kaptain-kavern/EcosystemOverhaul#24]
Some things that we may want to clean up on Github (based on the new direction of the mod):
- delete the "CKAPP-Food&DrugPack" branch
- delete textures for the food a drugs previously discussed (created)
- [x] ~~delete plant texture placeholders for the removed food plants~~
- [x]  ~~delete the toucan texture placeholder~~
- [x]  ~~delete any code associated with food and drugs~~
- [x]  ~~delete recipes~~

feel free to add to this list

**Comment by kaptain-kavern** [comment]
Do you mean all recipes and all foods? like in all, all ? with tobacco, vanilla chocolate and all of that ?

There are removed plant also ? (meaning just the one without textures yet ?)

As for the branch. It is more easy for me to work on the mods and his addons as a big mod (with all the files in the same place); and cut it in pieces afterwise. And Github release "post" will let me present the mod archive and all his add-ons on a single page for each release. So unless it is a big problem for you, it's more handy for me. If you prefer still I could manage, no problems :wink:

**Comment by lpCoercion** [comment]
I thought we decided to delete the CKAPP - Food & Drug Pack and focus on plants and animals for now, so that we could get releases out faster?

So, the only drugs would be dream vine (and neutromanine) and coffee beans. both of which will be in the core more. So, the CKAPP - Food & Drug Pack branch is no longer needed.

**Comment by kaptain-kavern** [comment]
And the Food & Drug Pack is completely forgotten or do you still want to do it later? Because adding animals and plants is not that hard (now that we are getting used to it also, it gets quicker) so I still could work on something else bit by bit alongside (but I can't seems to find textures for cigs and food and all).

Anyway i've removed all there I guess  --> https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/41fd9801abe73898e780b4e603f7f7280e84e47e

**Comment by lpCoercion** [comment]
we can just forget about it for now. I removed my post with the textures to avoid confusion, but I can post them here if you want them for reference.

**Comment by kaptain-kavern** [comment]
If you can and if your still planning on doing the FD pack (even later), I could work in advance when I have time, that way.

**Comment by lpCoercion** [comment]
alright. I figure that tou are busy enough with all of your other projects, so no need to add another.

**Comment by kaptain-kavern** [comment]
Oh you know, I'm the kind of person that doesn't properly works at 100% unless when I'm being buried under too much works ^^

And as we are almost done with the next release ... :smiley:

**Comment by lpCoercion** [comment]
dont worry. We will find something for you to do. This weekend I can pile animal textures on you :P

**Comment by lpCoercion** [comment]
Also, if you get bored, you could always start adding the other biomedefs and vanilla animal defs so we can start balancing stats and antlers, shearable, milk, etc to the vanilla animals
