### ISSUE TITLE
Plants regrowing too fast / needs way for clearing plants

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/EcosystemOverhaul#27]
Reported several times : "The plants are regrowing too quickly"

And while I find true that it is not realistic, I kinda like it that way. It forces me to use floors a lot more (I barely use them in Vanilla).

But if we were to try to address that, what can we do/try ?
- Actually changing this in the code. 
  But it's not as simple as if there was a single def called "regrowing potency" to change. It's the conjugation of all our changes that blend into this particular result - I will need to search/learn/experiment what changes will have more impact, etc ...
- Maybe add a cheap floor in wood, or something like "cobblestone" (floor made with rocks that were just lying around) : no/low resource cost - no movement bonus - no or negative beauty buff
- Something else  

---

doing some search on the web to find clearings method : 
- fire
- animals (especially grazers like sheep/ibex/goat)

**Comment by lpCoercion** [comment]
I actually like how it is currently. It adds a level of difficulty and a unique aspect to the biome.

I like your "flatten earth (floor)" idea. It allows you to stop plant growth without ruining the plant density of the biome.

Some concerns though: this adds an element that is not really related to the rest of the mod. It also may clutter the floor tab for players who dont want\need it. Also, I have found wood to be so abundent, it is practically free (e.g. a mahogany tree drops close to 100 wood), so the wood floor is a vanilla option already in game.

**Comment by kaptain-kavern** [comment]
That's how I do as well. Wood flooring (I also installed a mod for resource-free cobblestone - you can see it in most of my screenshots - but I had to mod it because the "free" floor was also having beauty and movement bonus - this was too OP for me).

That's why I was proposing the idea but I have no problem with the wood flooring vanilla unless that they look/feel weird (to me) when used outside :wink:

---

This is more what I had in mind when I was thinking _primitive_ way of "using wood for floor, in order to stop the forest" or make path
![this](https://thumbs.dreamstime.com/z/chemin-de-rondin-41354115.jpg)

Or this : 
![this](http://4.bp.blogspot.com/-w_KdDJpz6EQ/VX6LP6vQiqI/AAAAAAAAJvs/UkQYwytPpDU/s640/6%2B-%2Bhow-to-do-wooden-logs-floor-on-your-own-at-home.jpg)
But even this one seems like it would require more works than the first one

**Comment by lpCoercion** [comment]
I have no idea how this will look in game... but if you want to try it out, this would be a free floor tile:

trampled earth (jungle)

![trampledearth](https://cloud.githubusercontent.com/assets/22029252/19835996/a3405b5c-9e6a-11e6-9b83-da793571f6de.png)

The idea is that you stomp/crush all of the plants there making a layer of dead plants.

version without lines:

![trampledearthnl](https://cloud.githubusercontent.com/assets/22029252/19836003/fb0eed08-9e6a-11e6-9906-1e042fc90c33.png)

**Comment by kaptain-kavern** [comment]
Oh nice. I will try to make something and post you the result of the experiment ;-)

Just reading your phrase make me think of something : As it's specifically stomped **plants**, I very would like it to be only placeable on plants (or at least soil/gravel - terrain with plants). I don't know how I will do this right now but it's an idea ;-)

Also I will try with both but what is the idea behind having the textures with lines?

**Comment by lpCoercion** [comment]
the texture without lines may make a recoginizable pattern and look odd. the lines may be dark enough to blend into the dirt and create a more uniform floor/texture but I dont know. it may look bad lol

**Comment by kaptain-kavern** [comment]
Okey so I have spend several hours learning/testing how all of that is working. 
- In order to keep a visual logic and right scale the texture image have to be way much bigger. In vanilla and all "floors mods" I found; all floors are using 1024x1024 files.

> **Vanilla textures files :** 
> ![genericfloortile](https://cloud.githubusercontent.com/assets/2794612/19865558/047324a8-9f9d-11e6-897b-c949e935d5a0.png) ![soil](https://cloud.githubusercontent.com/assets/2794612/19865572/1d6612b8-9f9d-11e6-8dd7-424b22d85613.png)
- The game doesn't like at all the transparency with floor texture lol. I had strange graphical bugs/glitches until I copy paste your texture (with transparency over the vanilla soil texture) as a dirty fix.

So in the end I managed to produce a 1024x1024 one with no transparency (as explained above - [using this tuts](http://www.gimpusers.com/tutorials/create-repeatable-seamless-textures)) at somewhat the right scales. ~~I will put screenshots soon after, but~~ I'm sure - with all this knowledge and ~~with soon to be added~~ screenshots - you will be able to make a better texture than what I've done.

> **Texture I managed to make :**
> ![trampledearthfloor](https://cloud.githubusercontent.com/assets/2794612/19867481/46f3c5a6-9fa4-11e6-89c6-65e7f7d4b62e.png)  
> With line :
> ![trampledearthlinefloor](https://cloud.githubusercontent.com/assets/2794612/19867482/46f99a80-9fa4-11e6-834a-eb66d7917d30.png)
> 
> **In situ :**
> ![Imgur](http://i.imgur.com/4HKG1Fq.png?1)

---

---

Some crazy tests ^^ : 
![Natural Floor - Several textures test](http://i.imgur.com/aR59QWf.png?1)
![Imgur](http://i.imgur.com/v0oMuBh.png?1)
![Imgur](http://i.imgur.com/2Hc1vGb.png)

---

---

On an other hand, I will definitively look at the plants balancing this evening now that the spreadsheet is complete

**Comment by lpCoercion** [comment]
I really like the textures. The one with lines may look more filled in? maybe we could just make it grass and call it "common bahia".

Should we make it a floor or a crop with a really long lifespan?

**Comment by kaptain-kavern** [comment]
The cons about making it a crop is that it will require growing enabled (kind of counter intuitive having growing skill required to cut plants down ^^ ) I'm more for the floor solution. I will push it right now, with the lined textures then, and give you the link for you to test

**Comment by kaptain-kavern** [comment]
You could download this (https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/archive/master.zip) to test the very last version (including the Trampled earth floor).

That way you can test it and tell me if you prefer we try it as a crop

**Comment by lpCoercion** [comment]
I can test it in a few hours. Will it break my existing save? Using floors will require construction skill though so also counter intuitive. 

also, from your screenshots, the brown and red floors seem to have too much detail for RW

**Comment by kaptain-kavern** [comment]
In the mod I only include this one                 

> ![.](https://camo.githubusercontent.com/e138f422261fe91d5e85b94557ba57c5267a67f0/687474703a2f2f692e696d6775722e636f6d2f34484b473146712e706e673f31)

**Comment by lpCoercion** [comment]
due to halloween, i was unable to test this out last night. i will try and look at it tonight though

**Comment by kaptain-kavern** [comment]
No problems :wink:

Here in France it's not really celebrated a lot (even though it is more nowadays than say 15 years ago when I was kiddo) so it just means I had more free time to work yesterday :-)

Today was a "non-worked day" but I have more worked on a side project I have : I'm updating _[Superior Crafting](https://ludeon.com/forums/index.php?topic=11741)_ to A15 (from A11 ... the shit is full of red errors lol)

But as soon as have feedbacks from you for the floor or plants I will switch to working on our mod ;-)

**Comment by lpCoercion** [comment]
oh ok cool :)

yeah halloween is celebrated by most here.

did you want to release v1.3.1 now with the following updates (from the checklist) or wait for the floor/plants?
- ~~"hive tree" should be called "bee hive"~~ Done
- ~~"dream vines" should be called "dream vine"~~ Done
- ~~"dream vine root" should be called "dream root"~~ Done
- ~~the apiary should take up one tile (it is too big)~~ Done
- ~~after injesting enough dream root the pawn gets the mood buff "warm... inhebrated after drink". this is from beer I assume and should be changed to something like "sedated: I am relaxed and feeling good."~~ Done
- the dream root high is not shown in the health tab like the caffeine (or any other drug) high is  
  >_The first Hediff stage are hidden by/in vanilla, if the pawns reach a higher state it will be shown - You can still display them with "Dev mode"_  
- ~~food bills should be removed from coffee beans and dream root. it is a pain to micro manage the food recipes and doesnt seem to matter much after all~~ [Done](https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/84631c5e2902e7c21d4fcda795d69625fb101c1a)
- ~~tiger and jaguar should be slightly more common~~ Done
- ~~peafowl should be more rare~~ Done
- ~~jungle fowl should be slightly more rare~~ Done
- ~~dream vine should be more rare~~ Done
- ~~makes changes to plant statistics~~ [Done](https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/e4ef2f4114e3629d6d8acee24d4b70f7f88fb184)

**Comment by lpCoercion** [comment]
can you send me the texture you ended up using for the ground cover?. If we place it as a crop, we could have multiple (5-6) similiar randomly placed textures, so it looks more natural.

**Comment by lpCoercion** [comment]
or,.. maybe you could have more than one plant spawn in a tile like the ferns? we could also add an adult texture that has weeds and stuff if you dont mantain it?

**Comment by lpCoercion** [comment]
also... after a long time (year?) the crops could be harvested for "common bahia" which acts identical to hay

**Comment by lpCoercion** [comment]
if we do it rhat way i can also have the texture look similoar to vanilla grass

**Comment by kaptain-kavern** [comment]
Here for the texture : 
https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/blob/master/Textures/Terrain/Surfaces/TrampledEarthLineFloor.png

**Comment by lpCoercion** [comment]
oh ok thanks. I may make some edits to it.

Another option we have is to do both:
1. add a "trampled earth" floor (compacted dirt/rocks)
2. add a few grass crops behind a "sod farming" research for lawns

https://upload.wikimedia.org/wikipedia/commons/e/eb/Golf_bunkers_Filton.jpg
