### ISSUE TITLE
Conflict with EDB Prepare carefully

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/EcosystemOverhaul#28]
Reported by @tammabanana

> From forum thread : https://ludeon.com/forums/index.php?topic=26265.msg275007#msg275007

**Comment by kaptain-kavern** [comment]
As I don't use PC mod at all, and never have; I can't say nothing more than : "I will investigate"

**Comment by lpCoercion** [comment]
I dont use EDB prepare, but I dont see why it would create an issue. I assume it is all done using C# and it takes place during game creation.

**Comment by lpCoercion** [comment]
any ideas on this? I will ask skully if he knows. I think hes the author

**Comment by lpCoercion** [comment]
I talked to skullywag (author of EDB) on discord. He said the following:
- install both mods
- in the options of the game turn on verbose logging
- start the game and go to the animal screen in question
- quit game and check logs under: rimworld(version)_data/output.log

He posted on the thread too.

**Comment by lpCoercion** [comment]
well its actually not skullywags mod, but he is still looking into it lol

**Comment by kaptain-kavern** [comment]
Yep that the process I intend to follow. (Debugging is always start by this steps ;-) )

In fact the original modder's name was EDB but he quit recently, letting his mods open to be maintained by others. There was a time you couldn't find a player that doesn't play with some of EDB's mods (quite a few have been integrated in the base game over the time). 

Anyway I will look into it, I was just not finding it that "urgent" because of the workaround existing by using scenario feature

**Comment by lpCoercion** [comment]
ah ok. we could push it out with v1.3.1 if it is an easy fix. I may have found it after talking with skully?

```
<label>junglefowl</label>
    <race>CK_Junglefowl</race>
    <!--<labelMale>jungle peacock</labelMale>-->
    <labelFemale>jungle hen</labelFemale>  
```

removing the comment and making this 

`<labelMale>junglefowl</labelMale>`

may fix the issue?

**Comment by lpCoercion** [comment]
skully said that labels and gender have to be set for EDB. my other thought would be somewhere where the art placeholder animals were commented out?

**Comment by kaptain-kavern** [comment]
Here is the fix : https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/bf3b2e9e981871274dac3a9e50de541c697939ab

It was because of code I left about Toucan (The code was still there but not the texture - that's where the error came from). Now it can start without problems

**Comment by lpCoercion** [comment]
awesome :) I let the forum know
