### ISSUE TITLE
[Debate]About modded PackAnimal

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/EcosystemOverhaul#3]
_PackAnimal_ defs are "**_called**_" from : 
1. the _<BiomeDef><allowedPackAnimals>_ tag in **/Core/Defs/BiomeDefs/Biomes_XXX.xml**
2. the _<pawnGroupMakers><li Class="PawnGroupMaker_Trader"><carriers>_ tag in **/Defs/FactionDefs/Factions_Misc.xml**

This mean that we have to fiddle with those defs if we want to add or remove _packAnimal_ to existing vanilla trading factions. No problem for the first because we already have a modded Biomes_XXX.xml files. It's for the second part we have decisions to make. We have several options in order to implement them (sorted by difficulty order) : 
- Completely overwrite the defs and rewrite them just as vanilla's one except our added or removed _packAnimals_ :  

> But this mean **potential** compatibility issues with other mods that mod the same defs (with **potential** solutions just by changing both mods locations in mod order list) - _This I know how to do and had already done it_
- Write a completely new faction (maybe even a new trader : Animals trader) packed with the mod that will use all the modded packAnimal in the mod :  

> To me this is the better solution because we address the compatibility issues from modding vanilla factions and avoid CCL dependency (and also avoid complexity - for me - even if it is the simplest way of having complex modded  behaviour reserved to C# modders)
- Use _**CCL** injector's_. From what I understand about that (and I don't understand a lot when it comes to C# believe me) it permit to just insert a value in a def (Here we could just erase and/or add a packAnimal in Vanilla faction defs) :  

> This mean _**total compatibility** with any mods_ but we end up with this mod **having CCL as a dependency** (Some of my mods are done that way and I believe it is great nonetheless because it permit to use complex modding with only XML knowledge) - _I already had used CCL library but not the particular injector method_ 

---

---

---

Also what do you think about having another textures for pack Animals like this : 
![Pack Muffalo](https://i.imgur.com/sXbGWNt.png) 
or 
![Pack Mamuffalo](https://s25.postimg.io/rcn5kd4vz/Pack_Mamuffalo_side.png)

See this thread : https://ludeon.com/forums/index.php?topic=25580.msg260000#msg260000

**Comment by kaptain-kavern** [comment]
For permitting the project to advance I currently overwriting Vanilla traders defs value in **/Defs/FactionDefs/Factions_Misc.xml** (1rst solution above)

**Comment by kaptain-kavern** [comment]
![Poorly made PackElephant](https://i.imgur.com/MtqtMzJ.jpg)

I managed to commit this ^^

**Comment by lpCoercion** [comment]
Can you use this for the Pack Elephants?

![packelephantsaddle_side](https://cloud.githubusercontent.com/assets/22029252/18440002/773876d0-78d5-11e6-96c3-78972da18afd.png)

I will make a back and front as well.

**Comment by kaptain-kavern** [comment]
![elephant_back](https://cloud.githubusercontent.com/assets/2794612/18442275/6a20f234-7910-11e6-9e80-9103a3fdfe35.png)![elephant_front](https://cloud.githubusercontent.com/assets/2794612/18442272/69f86c42-7910-11e6-8ce6-ea79ff5801a3.png)![elephant_side](https://cloud.githubusercontent.com/assets/2794612/18442273/6a0acba8-7910-11e6-85b8-1aeedb92f28b.png)

Couldn't you do the trick with those vanilla elephant pictures ? (From [this thread](https://ludeon.com/forums/index.php?topic=2325.msg256247#msg256247) on the forum)
I'm not that efficient with Photoshop/Gimp/etc and the layers and all of that. 

If you can't I'll do, but I was in the impression you will be better than me with all of that ;)

I mean, it's not a layer with transparency I put on with XML code, for the packElephant I had to do it with Gimp (it is saved as a whole new image ![/](https://raw.githubusercontent.com/kaptain-kavern/EcosystemOverhaul/master/Textures/Things/Pawn/Animal/PackElephant_side.png) ) and it take me times because i'm not that experienced with all the transparency and layers etc

**Comment by lpCoercion** [comment]
If you want, we can just use the vanilla elephants, but if not, Ill create a new packs for it. I dont really want to use other mod artwork if we can avoid it.

**Comment by lpCoercion** [comment]
Since we are going to remove climate and weather changes from this mod, should we remove factions as well? Will it create compatibility issues and distract us from the main focus of the mod (adding plants and animals)? someone on the forums asked that we removed the factions.

**Comment by kaptain-kavern** [comment]
Yep i read that on the forum, I really don't see any reasons why adding a faction is a problem as the game mechanics should handle well any numbers of it. But the only reason for adding factions was to have a use for the modded pack animals, otherwise they will not be used at all (unless modding vanilla faction as described in OP : options 1 and 3)

**Comment by lpCoercion** [comment]
Yeah thats true. 

I will work on some new packs for the elephants.

**Comment by lpCoercion** [comment]
alright. lets just use the packs by **_anonymousfriend_** so that I can work on the plants and animals. let me know if you need me to place these over the elephant texture.

https://www.dropbox.com/s/q8k8jo5imwboydv/Pack%20Variants.rar?dl=0

![pack side](https://cloud.githubusercontent.com/assets/22029252/18593462/81e83642-7c09-11e6-899e-92b4e1950534.png)![1ri91yg](https://cloud.githubusercontent.com/assets/22029252/18593468/87317ca8-7c09-11e6-9273-076a98780136.png)![7cyxijj](https://cloud.githubusercontent.com/assets/22029252/18593473/8d1ddc88-7c09-11e6-9443-cfae5bc7c228.png)

**Comment by kaptain-kavern** [comment]
That's already what I used for the elephant ;)
If you can do better later then good, else I don't think it's that important :p
