### ISSUE TITLE
A16 (volunteering, if you're absent)

### ISSUE THREAD

**Issue by Tammabanana** [kaptain-kavern/EcosystemOverhaul#31]
Hi, guys! I've heard there's been Life putting modding on pause; I hope you're doing all right on that front.

I'm stopping by to inquire about your A16 plans, not because I demand you update, but rather to give you a chance to say, _Yes, we're here, don't touch!_ before I fork it in order to appease your rightfully adoring public.

(I'm not sure when exactly I would pick it up, but I should be able to do it sometime during winter break.)

**Comment by kaptain-kavern** [comment]
Sorry I was AWOL for a while. Are you still active ?

**Comment by Tammabanana** [comment]
I am! But on a very erratic basis - kids, life. I haven't looked at A17 with regards to plants or animals yet. What's the best way to give you the access to the A16 fork, so you can build off that if you want? (I left notes everywhere something changed.)

**Comment by kaptain-kavern** [comment]
I completely understand IRL sometimes happened ^^ It's the reason of my "absence" 😉 
______________

With Github I can re-fork your fork and Pull it in my repo, it's not a problem. I'm glad you did that and maintain the mod BTW. In fact it was the main reason I put my mods on Github.

And you left notes or comments on the changes you made! It's something even some "professional" developers are not doing. You rocks

**Comment by Tammabanana** [comment]
Awesome, I'm glad the re-forking will be easy. You'd mentioned before that you were into this sort of community upkeep, so I went for it!

"Professional", ha! My department has horror stories of the "bad old days", when certain staffers wouldn't keep notes on anything; some of the horror stories happened to me. Notes/comments are soooooo critical for long-term maintenance.
