### ISSUE TITLE
modded manhunter pack incidents

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/EcosystemOverhaul#4]
Adding allowed animals to manhunter pack incident.
- Vanilla's ones
  - Wolf (arctic and timber)
  - Bear (Grizzly and Polar)
  - Cassowary
- AnimalPack's ones
  - Gorilla
  - Komodo Dragon
  - Lion 
  - Hyena
  - Buffalo
  - Hippopotamus
  - Crocodile
  - Wolverine 
  - Mountain Lion
  - Coyote
  - Black Bear

We could add more even ... :wink:

**Comment by lpCoercion** [comment]
These should be added as manhunters for the tropical rainforest:

Gorilla
Jaguar
Komodo Dragon
Tiger
White Tiger
Python

**Comment by kaptain-kavern** [comment]
I just checked and I can't make biome specific incidents, if we add animals to the manhunter pack incident, added animals may show up in any biome.

I don't find that is a problem though, what about you?

**Comment by lpCoercion** [comment]
yeah thats fine. maybe we will figure out a work around in the future

**Comment by kaptain-kavern** [comment]
In fact I just found a way (a XML tag I haven't spotted earlier) and I can make manhunter incident tied to biomes :D 

The vanilla one is still there and been able to trigger on every biomes but I can add others specifically restricted to biomes, so I will do with the animals you listed above for tropical biome

I push it in the Dev branche : https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/c3dacfd98b05f5d1e6cbf8a2345fd0865e91a69a

**Comment by lpCoercion** [comment]
Can you tag the vanilla manhunters too? So that they dont appear in the rain forest?

**Comment by lpCoercion** [comment]
Can you tie the alpha beaver incident to specific biomes too? This shouldnt happen in the rainforest

**Comment by kaptain-kavern** [comment]
Yes I'm pretty sure I could (By redefining the code for the one from Vanilla). 

But regarding balance and at the speed our modded trees are growing I find it good to have something that can force player to react (or not). In the end we will go as you prefer it's simpler, that was just to understand your reasoning.

On a side note : make me think that we maybe can mod Vanilla elephants to eat trees as alphabeavers do ^^

**Comment by lpCoercion** [comment]
I really like that idea :)

lets do it. so remove alpha beaver incident and add an elephant herd incident to the rain forest?

**Comment by kaptain-kavern** [comment]
I was more saying "normal" elephant eating trees but I will look if I can do an alpha beaver incident using elephants. I like the idea too and hope it can be done

**Comment by kaptain-kavern** [comment]
I just checked and nope I can't make elephant appears instead of alphabeavers, maybe in the C# code (I mean that must not be that hard - i will look into that later). I look in the XML for the thrumbos event but it the same.

The best I can do is make normal elephants able to eat trees also (like Thrumbos in Vanilla) to have something that balance the removing of alphabeavers, if we remove them

**Comment by lpCoercion** [comment]
I dont think we should use C# for this.

Do alpha beavers really make a dent in the rainforest? As in, there are so many plants, do alpha beavers really matter?

maybe to balance out removing alpha beavers we increase the chance of toxic fallout or hives?

**Comment by kaptain-kavern** [comment]
In fact I even find them useful when I had some while testing. They were handy and they introduce some more game option (I was circumvent by raiders because alphabeavers had cleared a path in trees behind me defence) (that what make me thinks that having some animals, like elephants, eating trees can add fun)

While my tests, they never managed to clear all map trees, though

Again, just to discuss. If you prefer without no problems :p

**Comment by lpCoercion** [comment]
there was an interesting idea posted on the forum. would it be possible to spawn megatermite hives in the jungle that spawn megatermites? megatermites would multiply and focus on eating trees.

**Comment by kaptain-kavern** [comment]
Short answer : no. I mean it is a good idea and I'd love too but i'm pretty sure it can be done without C# modding. But hey hopefully you start to know me, I will think about it and try to find a trick :wink: 

Adding the animal that can eat trees isn't a problem, it's the mechanic used to bring them on the map. Alphabeaver or Thrumbo incident are not modifiable in XML (not the spawned animal at least). Trying with the manhunter incidents mechanics will not work because spawned animals by it are all in "manhunter" behaviour and aren't doing anything beside waiting for colonists to attack.

The last ways I can think of would be either via factions (but I've never tried to add mechanoids/animals or any non humanoid faction) or maybe via the infestation incident/code (I've never seriously look at it) but I don't expect it to be more modifiable than Alphabeavers one or other. 

If (and it's a big "if") we managed it one day to happen, it will not be for tomorrow... Too bad because I like the idea

**Comment by lpCoercion** [comment]
Well, should we start a "CK - Monster Pack" and add megatermites as wild spawn (defined in their def not biomedefs)?

**Comment by kaptain-kavern** [comment]
We mean another pack than the Dinosaurs' ? Because bigger insects may (or not) played well with dinosaurs, no ? I'm ok with both ways BTW :stuck_out_tongue:

**Comment by lpCoercion** [comment]
Well, I think the dinosaur pack should just be a biomesdef/xml that removes and adds certain plants and animals based on a prehistoric time period.

The giant insect pack/ monster pack would add new creatures on the creature's specific def. So it would be compatible with anything (and could be added to any game).
