### ISSUE TITLE
[Tropical Biome]Create new factions/traders

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/EcosystemOverhaul#5]

**Comment by kaptain-kavern** [comment]
Wilders are in. But I still struggling to have them with animals as part of the escort (I must miss an XML tag)

**Comment by lpCoercion** [comment]
Is the Class="PawnGroupMaker_Normal defined somewhere else without tigers in it?

Also, shouldnt the Pack Muffalo and Dromedary be set to 0?

We could add custom aromor. bone masks, etc.

**Comment by kaptain-kavern** [comment]
It is a Class used in each Faction <factiondefs> tags. 
Presently in the code I commented the line about Tiger to make the game ignore that line. 
If activated things work and the Tiger spawn with the group and seems to behave normally, but each time there is also an error message popping.

PackAnimals are restrain by the biome file firstly. In our Tropical Biomes files it is specified that the only PackAnimal allowed is PackElephant (regardless of factions).  
I left other PackAnimals in their GroupMaker in case the faction is used in other non-tropical biome. The game will throw an error if I let only PackElephant here when playing on Vanilla biome.

Also yes we could always expand and add more and more, but if you want my opinion/advice, in order to have something releasable (and to stay motivated) it's better to focus on a few little well-done-and-designed features (and expand on that after everything run smoothly) rather than trying to make a  never-truly-finished-wannabe-overhaul mod ^^

**Comment by lpCoercion** [comment]
Oh ok cool

Yeah good point. We could add to the faction later.. but they are kind of a secondary thought.

**Comment by kaptain-kavern** [comment]
Have you seen this on the forum ? : https://ludeon.com/forums/index.php?topic=24432.msg267982#msg267982

And what are your thoughts ?

**Comment by lpCoercion** [comment]
yeah. we can add those to the jungle traders. need outfits too though :P

I was thinking of making some weapons and armor for the wilders:

tribal headress, tribal clothes, etc.

birds could drop feathers (and would be needed to create these items at the craft station)

**Comment by kaptain-kavern** [comment]
With the next released in mind (new plants, crops, recipes, etc),  I went nuts and [progressed on several "fronts" yesterday](https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commits/dev), here is an update because I want to know if it suits you : 
- https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/11ad02b12cf3025ff4dbce1d420a293572763648 -  "Jungle Traders" now have their custom traderKind :
  Animal trader Caravan who sells all kind of animals, animal products,
  leather, meat, ... The caravan specifically always bring a few of the rarest of our modded animals (Panda,
  White Tiger, Komodo Dragon and Python - when they'll be added)

**Comment by lpCoercion** [comment]
looks good :)

Can you please check out the checklist issue?

https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/issues/2#issuecomment-250930615

**Comment by lpCoercion** [comment]
I think we should completely remove the Wilder faction. I think we should then move the Jungle Traders to a "CK - Faction Pack add-on". We can have traders for every biome in the pack.

**Comment by kaptain-kavern** [comment]
I erased the "Wilder" faction (https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/0fffc109ad39fce67cc823fdb6f8f24eac94e21a). 

I'm not against make things optional but if we remove the trader faction we don't have a way to buy new animals (unless if we mod a vanilla one and then it can lead to incompatibility). 
To be precise, standard vanilla traders that bring animals have a chance to have the new ones too alongside vanilla ones, the custom trader is for having a trader that bring specifically our added animals or future items. (also it's a completely new TraderKindDef and factionDef so there will be no compatibility issue if we keep it in).
Again I'm not against either way, it's more for you to consider everything before deciding

**Comment by lpCoercion** [comment]
I think we should remove everything from the Jungle Traders faction except for their ability to sell new plants, animals and items.

then, in the future we can add a faction pack that gives their elephants backpacks, faction members new equipment, etc.

**Comment by kaptain-kavern** [comment]
(sorry for the "silence", it was A Dog Said update day today ^^)

So it's kind of already the case. I will post what I've done in the code with explanation so you too can also changes as you feel

**Comment by lpCoercion** [comment]
oh ok cool

**Comment by kaptain-kavern** [comment]
Ok this will be a long post with code ^^ : 

---

So in faction def [(`/CK_AnimalPlant_Pack/Defs/FactionDefs/Factions_Misc.xml`)](https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/blob/dev/Defs/FactionDefs/Factions_Misc.xml) there are some `<tags>` that "tell" TraderKinds they are allowed to used.

---

Here in our JungleTrader faction : 

```
    <caravanTraderKinds>
      <li>Caravan_Outlander_BulkGoods</li>
      <li>CK_Caravan_Outlander_Animal_Traders</li>
      <li>Caravan_Outlander_Exotic</li>
      <li>Caravan_Outlander_PirateMerchant</li>
    </caravanTraderKinds>
    <visitorTraderKinds>
      <li>Visitor_Outlander_Standard</li>
    </visitorTraderKinds>
```

Those _TraderKinds_ def are located in [`CK_AnimalPlant_Pack/Defs/TraderKindDefs/`](https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/blob/dev/Defs/TraderKindDefs/TraderKinds_Caravan_Outlander.xml) and look like that : 

```
    <stockGenerators>
      <li Class="StockGenerator_SingleDef">
        <thingDef>Silver</thingDef>
        <countRange>
          <min>1500</min>
          <max>4000</max>
        </countRange>
      </li>
```

This is setting the trader to have between 1500 and 4000 silver units - can be any thing in `<thingDef>` like for component behind and such. You can also use the `<price>` tag (like for cloth code lower in the file) with Normal, Cheap value to set the trader to increase or decrease some prices (you know the one in green or red in the trading screen?).

---

This

```
      <li Class="StockGenerator_Category">
        <categoryDef>MeatRaw</categoryDef>
        <thingDefCountRange>
          <min>3</min>
          <max>7</max>
        </thingDefCountRange>
        <price>Cheap</price>
        <totalPriceRange>
          <min>350</min>
          <max>900</max>
        </totalPriceRange>
      </li>
```

is "telling the game" to generate several random items from one category (with `<categoryDef>`) for the trader to have, with a tag for setting price/value limit.

---

This

```
 <li Class="StockGenerator_MultiDef">
        <thingDefs>
          <li>Chocolate</li>
          <li>Kibble</li>
          <li>Pemmican</li>
        </thingDefs>
      </li>
```

permit to add some items regarding of their category

---

```
<li Class="StockGenerator_BuyWeirdOrganic" />
```

This I'm not exactly sure how to "translate", i'm pretty sure it permit this trader to buy our `<Exotic>` item (antlers and horns)

---

There is also a specific code for animals where you define which animals with the `<tradeTags>` tag: 

```
      <li Class="StockGenerator_Animals">
        <checkTemperature>true</checkTemperature>        
        <tradeTags>          
          <li>CK_RareAnimal</li>
        </tradeTags>
        <kindCountRange>
          <min>1</min>
          <max>3</max>
        </kindCountRange>
        <countRange>
          <min>2</min>
          <max>6</max>
        </countRange>        
      </li>
```

This bit is for adding our modded animals (`<li>CK_RareAnimal</li>` in `<tradeTags>`), notice the `<kindCountRange>` for defining number of different species and the `<countRange>` for how many animals for each species

**Comment by lpCoercion** [comment]
this looks good :) maybe we should make the min countrange 3 and the max kindcountrange 6?

**Comment by lpCoercion** [comment]
As discussed, the factions will be removed from this mod.

**Comment by kaptain-kavern** [comment]
https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/commit/48940c861748a5f585cb396996d4267d49846d0f

## Completely remove custom faction/changes to Traders

Without factions, no way for introducing a trader with necessarily our
animals. So I made a _compromise_ like that :
In place of completely erasing our custom trader, I "just" overwrite
one vanilla traders (only by adding a slot for CK_Animals in his stock -
so no major changes). That way in case of another mod doing changes on
the same files, we just "loose" that and that's all (vanilla traders
will still retain the possibility to bring modded animals alongside
vanilla ones)

Tell me what you think. Else it's just a file/folder to erase :wink:

**Comment by lpCoercion** [comment]
sounds good :)
