### ISSUE TITLE
[Tropical Biome]Modified Weather

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/EcosystemOverhaul#7]

**Comment by lpCoercion** [comment]
It looks like some of the code is off in the BiomeDefs.

desired:

<Tropical_Clear>2</Tropical_Clear>
<Tropical_Fog>2</Tropical_Fog>
<Tropical_Rain>18</Tropical_Rain
<Tropical_DryThunderstorm>0</Tropical_DryThunderstorm
<Tropical_RainyThunderstorm>6</Tropical_RainyThunderstorm
<Tropical_FoggyRain>4</Tropical_FoggyRain>

current:
<Tropical_Clear>15</Tropical_Clear>
<Tropical_Fog>2</Tropical_Fog>
<Tropical_Rain>18</Tropical_Rain
<Tropical_DryThunderstorm>1</Tropical_DryThunderstorm
<Tropical_RainyThunderstorm>8</Tropical_RainyThunderstorm
<Tropical_FoggyRain>4</Tropical_FoggyRain>

**Comment by lpCoercion** [comment]
Well, it deleted my code... but here is what it should be:

Tropical_Clear: 2
Tropical_Fog: 2
Tropical_Rain: 18
Tropical_DryThunderstorm: 0
Tropical_RainyThunderstorm: 6
Tropical_FoggyRain: 4
