### ISSUE TITLE
Advanced Mechanics

### ISSUE THREAD

**Issue by lpCoercion** [kaptain-kavern/EcosystemOverhaul#9]
Can the following advanced mechanics be added:

1) Rafflesia give an ugly enviornent debuff (like a corpse would) until cut. 

~~2) A Komodo Dragon bite causes a bacterial infection disease.~~ _Done_

**Comment by kaptain-kavern** [comment]
Yep doable also, for both.
1. Codewise it will work like flowers work in Vanilla but I will inverse the beauty bonus to a malus. ( :bulb: Good idea BTW :bulb: )
2. In fact I was about to talk you about the Komodo bites. I'm sure I can use the code for snake bite and tweak it a bit

**Comment by lpCoercion** [comment]
wow you work fast. cool

**Comment by lpCoercion** [comment]
I had another idea... Is it possible to replace "wild" rock chunks with moss covered rock chunks?

**Comment by kaptain-kavern** [comment]
This one may be harder to implement. From my first investigation it seems like rock are defined and spawn with another file than the biomes one. It is link to the "mapgeneration thing", something I've never mod. 

I will still look about that, not as a priority but still, because on paper it seems doable ;-p

**Comment by lpCoercion** [comment]
Alright let me know. If not, not a big deal.

**Comment by lpCoercion** [comment]
I was talking with dubwise (mars mod) who had a cool mechanic idea for down the road (would require C#... 

instead of the python or boa attacking, it gets a job. if the yellow progress bar fills up all the way, it constricts its victim to death
